version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: zantara-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  zantara-app:
    build: .
    container_name: zantara-bridge
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./service-account-key.json:/app/service-account-key.json:ro
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis-data:
    driver: local