global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "security_rules.yml"
  - "performance_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Zantara Bridge application metrics
  - job_name: 'zantara-bridge'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Adjust port as needed
    scrape_interval: 10s
    scrape_timeout: 5s

  # Google Cloud Run metrics (if deployed)
  - job_name: 'cloud-run-zantara'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['zantara-chat-v3-1064094238013-himaadsxua-et.a.run.app']
    scheme: https
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'