import cron from "node-cron";
import { uploadTextAsDoc } from "../services/driveUpload";

export function startCronTestSalvataffio() {
  // Ogni notte alle 03:00
  cron.schedule("0 3 * * *", async () => {
    console.log("⏰ Avvio heartbeat: Test Salvataffio Notturno");

    try {
      const timestamp = new Date().toISOString();
      const dateReadable = new Date().toLocaleDateString('id-ID', { 
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' 
      });
      
      const heartbeatContent = `🩺 ZANTARA HEARTBEAT - SALVATAFFIO NOTTURNO
===============================================
Timestamp: ${timestamp}
Readable Date: ${dateReadable}

✅ SYSTEM STATUS:
- ZANTARA Bridge: ACTIVE
- Drive Integration: OPERATIONAL  
- Service Account: WORKING
- OAuth Delegation: ACTIVE
- AMBARADAM Access: CONFIRMED

🔧 TECHNICAL INFO:
- Cron Job: 0 3 * * * (03:00 daily)
- Service: zantara@involuted-box-469105-r0.iam.gserviceaccount.com
- Target User: zero@balizero.com
- Folder ID: 1UGbm5er6Go351S57GQKUjmxMxHyT4QZb

🎯 PURPOSE:
This automated heartbeat ensures the ZANTARA system is:
1. Running continuously
2. Able to access Google Drive
3. Saving documents to AMBARADAM
4. JWT delegation working properly

📊 MONITORING:
If you see this file daily in AMBARADAM, 
all core systems are operational.

---
Generated by ZANTARA Heartbeat Cron Job
Next heartbeat: ${new Date(Date.now() + 24 * 60 * 60 * 1000).toLocaleDateString('id-ID')} 03:00`;

      const result = await uploadTextAsDoc(
        heartbeatContent,
        `Heartbeat Salvataffio – ${timestamp}`,
        "ZANTARA_SYSTEM"
      );

      console.log("✅ Salvataffio notturno completato:", result);
    } catch (err: any) {
      console.error("❌ Errore heartbeat salvataffio:", err.message);
      
      // Try fallback to simple upload
      try {
        console.log("🔄 Tentativo fallback...");
        const { uploadToDrive } = await import("../services/driveUpload");
        
        const fallbackContent = `ZANTARA HEARTBEAT FALLBACK - ${new Date().toISOString()}\n\nHeartbeat fallback attivo. Sistema operativo ma con limitazioni.\n\nGenerated by cron job fallback.`;
        
        await uploadToDrive(
          Buffer.from(fallbackContent).toString('base64'),
          `heartbeat-fallback-${Date.now()}.txt`,
          "ZANTARA_SYSTEM",
          "text/plain"
        );
        
        console.log("✅ Fallback heartbeat salvato");
      } catch (fallbackErr: any) {
        console.error("❌ Anche il fallback è fallito:", fallbackErr.message);
      }
    }
  });
  
  console.log("⏰ Cron job heartbeat salvataffio avviato (ogni giorno alle 03:00)");
}