openapi: 3.0.1
info:
  title: Zantara API
  version: '1.0'
servers:
  - url: https://your-domain
paths:
  /actions/codex/dispatch:
    post:
      operationId: dispatchCodex
      summary: Dispatch a task to Codex
      security:
        - bearerAuth: []
      parameters:
        - name: X-Idempotency-Key
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [event_type,payload]
              properties:
                event_type:
                  type: string
                payload:
                  type: object
                  additionalProperties: true
      responses:
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id: { type: string }
                  status: { type: string }
  /actions/codex/status/{request_id}:
    get:
      operationId: getCodexStatus
      summary: Get Codex task status
      security:
        - bearerAuth: []
      parameters:
        - name: request_id
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Status
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id: { type: string }
                  status:
                    type: string
                    enum: [queued, running, done, error]
                  output: { type: object, additionalProperties: true }
                  error: { type: string }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
