{
  "openapi": "3.0.1",
  "info": {
    "title": "Zantara Bridge API",
    "version": "1.0.0",
    "description": "API per gestire note, chat, e Drive Brief con autenticazione via X-API-KEY e X-BZ-USER."
  },
  "servers": [
    {
      "url": "https://zantara-chat-v3-1064094238013.asia-southeast2.run.app"
    }
  ],
  "paths": {
    "/health": {
      "get": {
        "summary": "Healthcheck",
        "responses": {
          "200": {
            "description": "Service is healthy"
          }
        }
      }
    },
    "/version": {
      "get": {
        "summary": "Version info",
        "responses": {
          "200": {
            "description": "Returns current version"
          }
        }
      }
    },
    "/api/notes": {
      "post": {
        "summary": "Crea una nuova nota",
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "name": "X-BZ-USER",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": { "type": "string" },
                  "content": { "type": "string" },
                  "dateKey": { "type": "string" }
                },
                "required": ["title", "content"]
              }
            }
          }
        },
        "responses": {
          "200": { "description": "Nota creata" }
        }
      },
      "get": {
        "summary": "Recupera note",
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "name": "X-BZ-USER",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "name": "dateKey",
            "in": "query",
            "required": false,
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": { "description": "Lista note" }
        }
      }
    },
    "/api/chat": {
      "post": {
        "summary": "Chatta con ZANTARA",
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "name": "X-BZ-USER",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "message": { "type": "string" },
                  "ririMode": { "type": "boolean" }
                },
                "required": ["message"]
              }
            }
          }
        },
        "responses": {
          "200": { "description": "Risposta dal modello AI" }
        }
      }
    },
    "/api/drive/_whoami": {
      "get": {
        "summary": "Mostra l'utente impersonato su Drive",
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "name": "X-BZ-USER",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": { "description": "Informazioni sull'utente impersonato" }
        }
      }
    },
    "/api/drive/brief": {
      "post": {
        "summary": "Genera e carica un brief in Google Drive",
        "parameters": [
          {
            "name": "X-API-KEY",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "name": "X-BZ-USER",
            "in": "header",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "dateKey": { "type": "string" },
                  "owner": { "type": "string" }
                }
              }
            }
          }
        },
        "responses": {
          "200": { "description": "File creato e indicizzato" }
        }
      }
    }
  },
  "components": {}
}
{
  "schema_version": "v1",
  "name_for_human": "Zantara Bridge",
  "name_for_model": "zantara_bridge",
  "description_for_human": "Gestisci note, chat AI e genera brief in Google Drive con autenticazione sicura.",
  "description_for_model": "Plugin che fornisce API per note, chat contestuale e generazione di brief su Google Drive. Richiede intestazioni X-API-KEY e X-BZ-USER.",
  "auth": {
    "type": "service_http",
    "authorization_type": "header",
    "verification_tokens": {}
  },
  "api": {
    "type": "openapi",
    "url": "https://zantara-chat-v3-1064094238013.asia-southeast2.run.app/.well-known/openapi.json"
  },
  "logo_url": "https://zantara-chat-v3-1064094238013.asia-southeast2.run.app/logo.png",
  "contact_email": "ops@balizero.com",
  "legal_info_url": "https://zantara-chat-v3-1064094238013.asia-southeast2.run.app/terms"
}
