#!/usr/bin/env bash
set -e
URL=$(gcloud run services describe zantara-chat-v3-1064094238013 --region asia-southeast2 --format='value(status.url)')
API_KEY="TEST_KEY_123"

echo "::1 calendar"; curl -s -X POST "$URL/actions/codex/dispatch" -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" -H "X-Idempotency-Key: cal-$(date +%s%N)" -d '{"event_type":"codex-task","payload":{"branch":"codex/calendar-real","repo":"Balizero1987/zantara_bridge","title":"feat(calendar): integrazione Google Calendar reale","body":"Usa SA_JSON_SECRET. Implementa create/get/list/update/delete/quickadd/freebusy; gestisci errori; aggiorna OpenAPI.","acceptance":{"curl_create":"POST /actions/calendar/create -> 201","curl_list":"GET /actions/calendar/list -> 200","openapi":"/.well-known/openapi.yaml include tutte le rotte calendar"},"prechecks":["no-main","run-tests:true","loc<=600"]}}'; echo

echo "::2 drive"; curl -s -X POST "$URL/actions/codex/dispatch" -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" -H "X-Idempotency-Key: drv-$(date +%s%N)" -d '{"event_type":"codex-task","payload":{"branch":"codex/drive-real","repo":"Balizero1987/zantara_bridge","title":"feat(drive): upload/list/save note su Google Drive","body":"Usa MEMORY_DRIVE_FOLDER_ID. Implementa upload/rename/move/share/permissions audit + list. Gestisci tipi MIME e errori 4xx.","acceptance":{"curl_upload":"POST /actions/drive/upload -> 200","audit":"/actions/drive/permissions/audit -> entries[]"},"prechecks":["no-main","run-tests:true","loc<=700"]}}'; echo

echo "::3 gmail"; curl -s -X POST "$URL/actions/codex/dispatch" -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" -H "X-Idempotency-Key: gml-$(date +%s%N)" -d '{"event_type":"codex-task","payload":{"branch":"codex/gmail-real","repo":"Balizero1987/zantara_bridge","title":"feat(gmail): invio email via Gmail API","body":"Usa SA_JSON_SECRET e GMAIL_SENDER. Implementa /actions/gmail/send con to/subject/text, validazione, error handling, OpenAPI.","acceptance":{"curl_send":"POST /actions/gmail/send -> 200 con messageId"},"prechecks":["no-main","run-tests:true","loc<=400"]}}'; echo

echo "::4 memory"; curl -s -X POST "$URL/actions/codex/dispatch" -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" -H "X-Idempotency-Key: mem-$(date +%s%N)" -d '{"event_type":"codex-task","payload":{"branch":"codex/memory-real","repo":"Balizero1987/zantara_bridge","title":"feat(memory): save+search note (Drive+Firestore)","body":"/actions/memory/save scrive file MD su Drive e metadati su Firestore; /actions/memory/search per keyword (titolo/summary).","acceptance":{"save":"POST /actions/memory/save -> 200 con link drive","search":"GET /actions/memory/search?q=foo -> items[].title"},"prechecks":["no-main","run-tests:true","loc<=700"]}}'; echo

echo "::5 openapi"; curl -s -X POST "$URL/actions/codex/dispatch" -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" -H "X-Idempotency-Key: oas-$(date +%s%N)" -d '{"event_type":"codex-task","payload":{"branch":"codex/openapi-complete","repo":"Balizero1987/zantara_bridge","title":"docs(openapi): espandi OpenAPI con tutti i path e schemi","body":"Aggiorna /.well-known/openapi.yaml con calendar/drive/gmail/memory/codex; aggiungi operationId, security, schemas coerenti.","acceptance":{"curl_oas":"GET /.well-known/openapi.yaml -> contiene tutti i path e schemi"},"prechecks":["no-main","run-tests:true","loc<=500"]}}'; echo

echo "::6 rate+log"; curl -s -X POST "$URL/actions/codex/dispatch" -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" -H "X-Idempotency-Key: rlog-$(date +%s%N)" -d '{"event_type":"codex-task","payload":{"branch":"codex/rate-log","repo":"Balizero1987/zantara_bridge","title":"feat(core): rate-limit globale e logging JSON con request_id","body":"Aggiungi middleware rateLimit (X-RateLimit headers) su /actions/* e logging JSON {ts,request_id,route,status,duration}.","acceptance":{"log":"/health produce log JSON","rl":"POST /actions/... ritorna X-RateLimit-*"},"prechecks":["no-main","run-tests:true","loc<=350"]}}'; echo

echo "::7 cicd"; curl -s -X POST "$URL/actions/codex/dispatch" -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" -H "X-Idempotency-Key: cicd-$(date +%s%N)" -d '{"event_type":"codex-task","payload":{"branch":"codex/cicd-cloudrun","repo":"Balizero1987/zantara_bridge","title":"ci: build+push Artifact Registry e deploy Cloud Run su merge main","body":"Workflow: on push main -> npm ci, tsc, docker buildx amd64, push AR, gcloud run deploy con env da Secret Manager.","acceptance":{"run":"Actions run green, Cloud Run revision aggiornata"},"prechecks":["no-main","run-tests:true","loc<=500"]}}'; echo

echo "::8 gateway"; curl -s -X POST "$URL/actions/codex/dispatch" -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" -H "X-Idempotency-Key: gw-$(date +%s%N)" -d '{"event_type":"codex-task","payload":{"branch":"codex/staff-gateway","repo":"Balizero1987/zantara_bridge","title":"feat(gateway): ponte API dipendenti con token staff","body":"Modulo /api/*: auth staff tokens, proxy verso /actions/* aggiungendo API_KEY di ZANTARA; audit basico.","acceptance":{"curl":"POST /api/dispatch con Bearer staff_token -> 202"},"prechecks":["no-main","run-tests:true","loc<=400"]}}'; echo
