name: 02 - Claude kickoff

on:
  repository_dispatch:
    types: [CLAUDE_REVIEW]

jobs:
  kickoff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Parse payload
        id: p
        run: |
          echo "PR_NUMBER=${{ github.event.client_payload.pr_number }}" >> $GITHUB_OUTPUT

      - name: Ask Claude for review (comment)
        uses: actions/github-script@v7
        with:
          script: |
            const pr = Number(core.getInput('pr', { required: true }));
            const body = [
              "[@claude] Security-first & correctness review, please.",
              "- Focus: Drive DWD impersonation (401), secrets mapping, CI smoke.",
              "- Return: Blocking/High/Medium with exact diffs/commands.",
            ].join("\n");
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body
            });
          result-encoding: string
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr: ${{ steps.p.outputs.PR_NUMBER }}
