name: 03 - Merge & Deploy on Claude LGTM

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    if: >
      (github.event_name == 'issue_comment' &&
       contains(github.event.comment.body, 'LGTM') ) ||
      (github.event_name == 'pull_request_review' &&
       github.event.review.state == 'approved')
    steps:
      - name: Resolve PR number
        id: pr
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Merge PR (squash)
        uses: actions/github-script@v7
        with:
          script: |
            const pr = Number(core.getInput('pr', { required: true }));
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr,
              merge_method: 'squash'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr: ${{ steps.pr.outputs.PR_NUMBER }}

      - name: Kick Deploy workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-cloudrun.yml',
              ref: 'main'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
