name: Smoke Postfix

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run smoke-postfix
        run: |
          chmod +x scripts/smoke-postfix.sh || true
          npm run smoke:postfix

